### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by mrmeloman** [ryankopf/wordsponge#2]
Your project is just the thing I wanted to create myself. Thank you kindly for your work. I'm interested in a couple of things.

1. Is the project still alive? By that I mean: would you still review possible contributions and do you try to keep the code relevant to new Chrome versions?
2. Readme has links to https://thewordsponge.com/ but the site is dead. Will it stay dead?
3. Readme also offers a link to the extension in the Chrome store. The link is dead, but there is an [extension with the same name](https://chromewebstore.google.com/detail/word-sponge/kiphhbngjiidccgcebflhlmmabighbem) there. Is this yours?

I can offer updates to the readme.md file based on your answers to the last 2 questions, so if you don't have the opportunity to do it - don't bother, I've got you. It would be a good gesture before trying to make some actual contributions. (=

**Comment by ryankopf** [comment]
1. I'm always open to PRs. I request they be clean and focused on one thing at a time.
2. I plan to come back and do some more work on this whenever I have time, but my time has been limited.
3. I'll update the links!
4. Thanks for reporting the website downtime, I have fixed that! :)
